version: "3.3"

services:

  db:
    image: postgres:12.2
    volumes: 
      - ./db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment: 
      - INFLUXDB_DB=db0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
